my_var1 = 5
my_var2 = 10

def my_func():
    my_var1=15
    print(my_var1)   
    print(my_var2)
    
my_func()
# ошибка не возни кадла из за того что переменная была определена ране